# Ścieżki do katalogów i ustawienia konfiguracyjne
#data_directory: "../data/meteo"
source_directory: "../data/meteo"
target_directory: "../data/flask_data/1_surface_0"

# Ustawienia htmx
htmx:
  trigger_interval: "1s"
