# Ścieżki do katalogów i ustawienia konfiguracyjne
data_directory: "../data"
data_directory_grib: "../data/meteo"
data_directory_flask: "../data/flask_data"
#target_directory: "../data/flask_data/"
# Ustawienia htmx
htmx:
  trigger_interval: "1s"
