version: '3.8'

services:
  flask_app:
    build: ./flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    depends_on:
      - grib_processing

  grib_processing:
    build: ./grib_processing
    volumes:
      - ./data:/data
